GET  http://localhost:5000/users
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZGFzY3NkZnNkZnNkQGdtYWlsLmNvbSIsImlkIjoiNjE0NzI4OTJkZGU3NzYxNDZmNDRlZDM5IiwiaWF0IjoxNjMyMDU5NjAzLCJleHAiOjE2MzIwNjY4MDN9.CpWHa03vaWh6PVGk3kLwTec9zwsHibUb72wp9Yvd6XY